title: Zhijie Gong's Homepage
page-top-title: Zhijie Gong
top-section-bg-text: Zhijie Gong's Homepage
home-subtitle: Zhijie Gong
email: zhijie123@mail.ustc.edu.cn
copyright-text: '&copy; Zhijie Gong 2023-2025. All Rights Reserved.'
